<?php

/**
 * PluginfpErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfpErrorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginfpErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginfpError');
    }
}